modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="bettercraft"
version="1.0.0"
displayName="BetterCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Icaro_Games_BR, MCreator"

[[dependencies.bettercraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




